type Key = keyof typeof DATA;
export type DataType = {
	[key: string]: {
		id: string;
		type: string;
		childId: Key[];
		parentId: Key | '';
		name?: string;
		title?: string;
		description?: string;
		status?: string;
		isCompleted?: boolean;
	};
};

export const DATA: DataType = {
	root: {
		id: 'root',
		type: 'root',
		childId: ['b01', 'b02', 'b03'],
		parentId: '',
	},
	b01: {
		id: 'b01',
		type: 'board',
		name: 'Platform Launch',
		childId: ['c01', 'c02', 'c03'],
		parentId: 'root',
	},
	c01: {
		id: 'c01',
		type: 'column',
		name: 'Todo',
		childId: ['t01', 't02', 't03', 't04'],
		parentId: 'b01',
	},
	t01: {
		id: 't01',
		type: 'task',
		title: 'Build UI for onboarding flow',
		description: '',
		status: 'Todo',
		childId: ['s01', 's02', 's03'],
		parentId: 'c01',
	},
	s01: {
		id: 's01',
		type: 'subtask',
		title: 'Sign up page',
		isCompleted: true,
		childId: [],
		parentId: 't01',
	},
	s02: {
		id: 's02',
		type: 'subtask',
		title: 'Sign in page',
		isCompleted: false,
		childId: [],
		parentId: 't01',
	},
	s03: {
		id: 's03',
		type: 'subtask',
		title: 'Welcome page',
		isCompleted: false,
		childId: [],
		parentId: 't01',
	},
	t02: {
		id: 't02',
		type: 'task',
		title: 'Build UI for search',
		description: '',
		status: 'Todo',
		childId: ['s04'],
		parentId: 'c01',
	},
	s04: {
		id: 's04',
		type: 'subtask',
		title: 'Search page',
		isCompleted: false,
		childId: [],
		parentId: 't02',
	},
	t03: {
		id: 't03',
		type: 'task',
		title: 'Build settings UI',
		description: '',
		status: 'Todo',
		childId: ['s05', 's06'],
		parentId: 'c01',
	},
	s05: {
		id: 's05',
		type: 'subtask',
		title: 'Account page',
		isCompleted: false,
		childId: [],
		parentId: 't03',
	},
	s06: {
		id: 's06',
		type: 'subtask',
		title: 'Billing page',
		isCompleted: false,
		childId: [],
		parentId: 't03',
	},
	t04: {
		id: 't04',
		type: 'task',
		title: 'QA and test all major user journeys',
		description:
			'Once we feel version one is ready, we need to rigorously test it both internally and externally to identify any major gaps.',
		status: 'Todo',
		childId: ['s07', 's08'],
		parentId: 'c01',
	},
	s07: {
		id: 's07',
		type: 'subtask',
		title: 'Internal testing',
		isCompleted: false,
		childId: [],
		parentId: 't04',
	},
	s08: {
		id: 's08',
		type: 'subtask',
		title: 'External testing',
		isCompleted: false,
		childId: [],
		parentId: 't04',
	},
	c02: {
		id: 'c02',
		type: 'column',
		name: 'Doing',
		childId: ['t05', 't06', 't07', 't08', 't09', 't10'],
		parentId: 'b01',
	},
	t05: {
		id: 't05',
		type: 'task',
		title: 'Design settings and search pages',
		description: '',
		status: 'Doing',
		childId: ['s09', 's10', 's11'],
		parentId: 'c02',
	},
	s09: {
		id: 's09',
		type: 'subtask',
		title: 'Settings - Account page',
		isCompleted: true,
		childId: [],
		parentId: 't05',
	},
	s10: {
		id: 's10',
		type: 'subtask',
		title: 'Settings - Billing page',
		isCompleted: true,
		childId: [],
		parentId: 't05',
	},
	s11: {
		id: 's11',
		type: 'subtask',
		title: 'Search page',
		isCompleted: false,
		childId: [],
		parentId: 't05',
	},
	t06: {
		id: 't06',
		type: 'task',
		title: 'Add account management endpoints',
		description: '',
		status: 'Doing',
		childId: ['s12', 's13', 's14'],
		parentId: 'c02',
	},
	s12: {
		id: 's12',
		type: 'subtask',
		title: 'Upgrade plan',
		isCompleted: true,
		childId: [],
		parentId: 't06',
	},
	s13: {
		id: 's13',
		type: 'subtask',
		title: 'Cancel plan',
		isCompleted: true,
		childId: [],
		parentId: 't06',
	},
	s14: {
		id: 's14',
		type: 'subtask',
		title: 'Update payment method',
		isCompleted: false,
		childId: [],
		parentId: 't06',
	},
	t07: {
		id: 't07',
		type: 'task',
		title: 'Design onboarding flow',
		description: '',
		status: 'Doing',
		childId: ['s15', 's16', 's17'],
		parentId: 'c02',
	},
	s15: {
		id: 's15',
		type: 'subtask',
		title: 'Sign up page',
		isCompleted: true,
		childId: [],
		parentId: 't07',
	},
	s16: {
		id: 's16',
		type: 'subtask',
		title: 'Sign in page',
		isCompleted: false,
		childId: [],
		parentId: 't07',
	},
	s17: {
		id: 's17',
		type: 'subtask',
		title: 'Welcome page',
		isCompleted: false,
		childId: [],
		parentId: 't07',
	},
	t08: {
		id: 't08',
		type: 'task',
		title: 'Add search enpoints',
		description: '',
		status: 'Doing',
		childId: ['s18', 's19'],
		parentId: 'c02',
	},
	s18: {
		id: 's18',
		type: 'subtask',
		title: 'Add search endpoint',
		isCompleted: true,
		childId: [],
		parentId: 't08',
	},
	s19: {
		id: 's19',
		type: 'subtask',
		title: 'Define search filters',
		isCompleted: false,
		childId: [],
		parentId: 't08',
	},
	t09: {
		id: 't09',
		type: 'task',
		title: 'Add authentication endpoints',
		description: '',
		status: 'Doing',
		childId: ['s20', 's21'],
		parentId: 'c02',
	},
	s20: {
		id: 's20',
		type: 'subtask',
		title: 'Define user model',
		isCompleted: true,
		childId: [],
		parentId: 't09',
	},
	s21: {
		id: 's21',
		type: 'subtask',
		title: 'Add auth endpoints',
		isCompleted: false,
		childId: [],
		parentId: 't09',
	},
	t10: {
		id: 't10',
		type: 'task',
		title:
			'Research pricing points of various competitors and trial different business models',
		description:
			"We know what we're planning to build for version one. Now we need to finalise the first pricing model we'll use. Keep iterating the subtasks until we have a coherent proposition.",
		status: 'Doing',
		childId: ['s22', 's23', 's24'],
		parentId: 'c02',
	},
	s22: {
		id: 's22',
		type: 'subtask',
		title: 'Research competitor pricing and business models',
		isCompleted: true,
		childId: [],
		parentId: 't10',
	},
	s23: {
		id: 's23',
		type: 'subtask',
		title: 'Outline a business model that works for our solution',
		isCompleted: false,
		childId: [],
		parentId: 't10',
	},
	s24: {
		id: 's24',
		type: 'subtask',
		title:
			'Talk to potential customers about our proposed solution and ask for fair price expectancy',
		isCompleted: false,
		childId: [],
		parentId: 't10',
	},
	c03: {
		id: 'c03',
		type: 'column',
		name: 'Done',
		childId: ['t11', 't12', 't13', 't14', 't15', 't16', 't17'],
		parentId: 'b01',
	},
	t11: {
		id: 't11',
		type: 'task',
		title: 'Conduct 5 wireframe tests',
		description:
			'Ensure the layout continues to make sense and we have strong buy-in from potential users.',
		status: 'Done',
		childId: ['s25'],
		parentId: 'c03',
	},
	s25: {
		id: 's25',
		type: 'subtask',
		title: 'Complete 5 wireframe prototype tests',
		isCompleted: true,
		childId: [],
		parentId: 't11',
	},
	t12: {
		id: 't12',
		type: 'task',
		title: 'Create wireframe prototype',
		description:
			'Create a greyscale clickable wireframe prototype to test our asssumptions so far.',
		status: 'Done',
		childId: ['s26'],
		parentId: 'c03',
	},
	s26: {
		id: 's26',
		type: 'subtask',
		title: 'Create clickable wireframe prototype in Balsamiq',
		isCompleted: true,
		childId: [],
		parentId: 't12',
	},
	t13: {
		id: 't13',
		type: 'task',
		title: 'Review results of usability tests and iterate',
		description:
			"Keep iterating through the subtasks until we're clear on the core concepts for the app.",
		status: 'Done',
		childId: ['s27', 's28', 's29'],
		parentId: 'c03',
	},
	s27: {
		id: 's27',
		type: 'subtask',
		title: 'Meet to review notes from previous tests and plan changes',
		isCompleted: true,
		childId: [],
		parentId: 't13',
	},
	s28: {
		id: 's28',
		type: 'subtask',
		title: 'Make changes to paper prototypes',
		isCompleted: true,
		childId: [],
		parentId: 't13',
	},
	s29: {
		id: 's29',
		type: 'subtask',
		title: 'Conduct 5 usability tests',
		isCompleted: true,
		childId: [],
		parentId: 't13',
	},
	t14: {
		id: 't14',
		type: 'task',
		title:
			'Create paper prototypes and conduct 10 usability tests with potential customers',
		description: '',
		status: 'Done',
		childId: ['s30', 's31'],
		parentId: 'c03',
	},
	s30: {
		id: 's30',
		type: 'subtask',
		title: 'Create paper prototypes for version one',
		isCompleted: true,
		childId: [],
		parentId: 't14',
	},
	s31: {
		id: 's31',
		type: 'subtask',
		title: 'Complete 10 usability tests',
		isCompleted: true,
		childId: [],
		parentId: 't14',
	},
	t15: {
		id: 't15',
		type: 'task',
		title: 'Market discovery',
		description:
			'We need to define and refine our core product. Interviews will help us learn common pain points and help us define the strongest MVP.',
		status: 'Done',
		childId: ['s32'],
		parentId: 'c03',
	},
	s32: {
		id: 's32',
		type: 'subtask',
		title: 'Interview 10 prospective customers',
		isCompleted: true,
		childId: [],
		parentId: 't15',
	},
	t16: {
		id: 't16',
		type: 'task',
		title: 'Competitor analysis',
		description: '',
		status: 'Done',
		childId: ['s33', 's34'],
		parentId: 'c03',
	},
	s33: {
		id: 's33',
		type: 'subtask',
		title: 'Find direct and indirect competitors',
		isCompleted: true,
		childId: [],
		parentId: 't16',
	},
	s34: {
		id: 's34',
		type: 'subtask',
		title: 'SWOT analysis for each competitor',
		isCompleted: true,
		childId: [],
		parentId: 't16',
	},
	t17: {
		id: 't17',
		type: 'task',
		title: 'Research the market',
		description:
			'We need to get a solid overview of the market to ensure we have up-to-date estimates of market size and demand.',
		status: 'Done',
		childId: ['s35', 's36'],
		parentId: 'c03',
	},
	s35: {
		id: 's35',
		type: 'subtask',
		title: 'Write up research analysis',
		isCompleted: true,
		childId: [],
		parentId: 't17',
	},
	s36: {
		id: 's36',
		type: 'subtask',
		title: 'Calculate TAM',
		isCompleted: true,
		childId: [],
		parentId: 't17',
	},
	b02: {
		id: 'b02',
		type: 'board',
		name: 'Marketing Plan',
		childId: ['c04', 'c05', 'c06'],
		parentId: 'root',
	},
	c04: {
		id: 'c04',
		type: 'column',
		name: 'Todo',
		childId: ['t18', 't19', 't20'],
		parentId: 'b02',
	},
	t18: {
		id: 't18',
		type: 'task',
		title: 'Plan Product Hunt launch',
		description: '',
		status: 'Todo',
		childId: ['s37', 's38', 's39', 's40', 's41', 's42'],
		parentId: 'c04',
	},
	s37: {
		id: 's37',
		type: 'subtask',
		title: 'Find hunter',
		isCompleted: false,
		childId: [],
		parentId: 't18',
	},
	s38: {
		id: 's38',
		type: 'subtask',
		title: 'Gather assets',
		isCompleted: false,
		childId: [],
		parentId: 't18',
	},
	s39: {
		id: 's39',
		type: 'subtask',
		title: 'Draft product page',
		isCompleted: false,
		childId: [],
		parentId: 't18',
	},
	s40: {
		id: 's40',
		type: 'subtask',
		title: 'Notify customers',
		isCompleted: false,
		childId: [],
		parentId: 't18',
	},
	s41: {
		id: 's41',
		type: 'subtask',
		title: 'Notify network',
		isCompleted: false,
		childId: [],
		parentId: 't18',
	},
	s42: {
		id: 's42',
		type: 'subtask',
		title: 'Launch!',
		isCompleted: false,
		childId: [],
		parentId: 't18',
	},
	t19: {
		id: 't19',
		type: 'task',
		title: 'Share on Show HN',
		description: '',
		status: '',
		childId: ['s43', 's44', 's45'],
		parentId: 'c04',
	},
	s43: {
		id: 's43',
		type: 'subtask',
		title: 'Draft out HN post',
		isCompleted: false,
		childId: [],
		parentId: 't19',
	},
	s44: {
		id: 's44',
		type: 'subtask',
		title: 'Get feedback and refine',
		isCompleted: false,
		childId: [],
		parentId: 't19',
	},
	s45: {
		id: 's45',
		type: 'subtask',
		title: 'Publish post',
		isCompleted: false,
		childId: [],
		parentId: 't19',
	},
	t20: {
		id: 't20',
		type: 'task',
		title: 'Write launch article to publish on multiple channels',
		description: '',
		status: '',
		childId: ['s46', 's47', 's48', 's49'],
		parentId: 'c04',
	},
	s46: {
		id: 's46',
		type: 'subtask',
		title: 'Write article',
		isCompleted: false,
		childId: [],
		parentId: 't20',
	},
	s47: {
		id: 's47',
		type: 'subtask',
		title: 'Publish on LinkedIn',
		isCompleted: false,
		childId: [],
		parentId: 't20',
	},
	s48: {
		id: 's48',
		type: 'subtask',
		title: 'Publish on Inndie Hackers',
		isCompleted: false,
		childId: [],
		parentId: 't20',
	},
	s49: {
		id: 's49',
		type: 'subtask',
		title: 'Publish on Medium',
		isCompleted: false,
		childId: [],
		parentId: 't20',
	},
	c05: {
		id: 'c05',
		type: 'column',
		name: 'Doing',
		childId: [],
		parentId: 'b02',
	},
	c06: {
		id: 'c06',
		type: 'column',
		name: 'Done',
		childId: [],
		parentId: 'b02',
	},
	b03: {
		id: 'b03',
		type: 'board',
		name: 'Roadmap',
		childId: ['c07', 'c08', 'c09'],
		parentId: 'root',
	},
	c07: {
		id: 'c07',
		type: 'column',
		name: 'Now',
		childId: ['t21', 't22'],
		parentId: 'b03',
	},
	t21: {
		id: 't21',
		type: 'task',
		title: 'Launch version one',
		description: '',
		status: '',
		childId: ['s50', 's51'],
		parentId: 'c07',
	},
	s50: {
		id: 's50',
		type: 'subtask',
		title: 'Launch privately to our waitlist',
		isCompleted: false,
		childId: [],
		parentId: 't21',
	},
	s51: {
		id: 's51',
		type: 'subtask',
		title: 'Launch publicly on PH, HN, etc.',
		isCompleted: false,
		childId: [],
		parentId: 't21',
	},
	t22: {
		id: 't22',
		type: 'task',
		title: 'Review early feedback and plan next steps for roadmap',
		description:
			"Beyond the initial launch, we're keeping the initial roadmap completely empty. This meeting will help us plan out our next steps based on actual customer feedback.",
		status: '',
		childId: ['s52', 's53', 's54'],
		parentId: 'c07',
	},
	s52: {
		id: 's52',
		type: 'subtask',
		title: 'Interview 10 customers',
		isCompleted: false,
		childId: [],
		parentId: 't22',
	},
	s53: {
		id: 's53',
		type: 'subtask',
		title: 'Review common customer pain points and suggestions',
		isCompleted: false,
		childId: [],
		parentId: 't22',
	},
	s54: {
		id: 's54',
		type: 'subtask',
		title: 'Outline next steps for our roadmap',
		isCompleted: false,
		childId: [],
		parentId: 't22',
	},
	c08: {
		id: 'c08',
		type: 'column',
		name: 'Next',
		childId: [],
		parentId: 'b03',
	},
	c09: {
		id: 'c09',
		type: 'column',
		name: 'Later',
		childId: [],
		parentId: 'b03',
	},
};
