import StyledComponentsRegistry from '@/components/StyledComponentsRegistry';
import GlobalStyles from '@/components/GlobalStyles';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';

const mainFont = Plus_Jakarta_Sans({
	subsets: ['latin'],
	display: 'fallback',
	weight: ['500', '700'],
	variable: '--font-family',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={mainFont.variable}>
			<body>
				<StyledComponentsRegistry>
					<GlobalStyles />
					{children}
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
